# Generated by Django 5.1 on 2024-08-27 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='perfil',
            new_name='perfil_endereco',
        ),
    ]
