# Generated by Django 5.1 on 2024-08-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_rename_perfil_endereco_perfil_endereco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
    ]
