# Generated by Django 5.1 on 2024-08-27 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_endereco_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
    ]
